language: node_js
node_js:
  - "0.12"
  - "0.10"
  - "0.8"
script:
  - npm test
  - npm install . -g
before_install:
  - npm install -g npm 
  - npm install -g cordova
  - sudo apt-get update -qq
  - sudo apt-get install imagemagick
